### ISSUE TITLE
Dependency not found

### ISSUE THREAD

**Issue by seufagner** [pingcap/tispark#106]
Which repository I should use to resolve dependency? I just try on Maven Central but it don't exists there.

build.sbt
`"com.pingcap.tispark" % "tispark_2.11" % "0.1.0-SNAPSHOT",`

Throws error:
`[error] (*:update) sbt.ResolveException: unresolved dependency: com.pingcap.tispark#tispark;0.1.0-SNAPSHOT: not found`

**Comment by Novemser** [comment]
We haven't put tispark on Maven Central, so you may need to compile source code of [tispark](https://github.com/pingcap/tispark) and build one for youself.

At last, don't forget to execute `mvn clean install` to install the tispark to your local maven repository.

Regards.

**Comment by seufagner** [comment]
Thanks for your reply.

@Novemser I already try this, but it has broken dependencies too, like tikv package. 
Sorry, but why don't put it on Maven Central, which the motivation?

```[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:47 min
[INFO] Finished at: 2017-12-01T19:06:35-02:00
[INFO] Final Memory: 20M/199M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project tispark: Could not resolve dependencies for project 
com.pingcap.tispark:tispark:jar:0.1.0-SNAPSHOT: Could not find artifact com.pingcap.tikv:tikv-client:jar:0.1.0-SNAPSHOT -> [Help 1] 

Thanks for your reply

**Comment by Novemser** [comment]
@seufagner Sorry for the inconvenience we brought, putting TiSpark on Maven Central is in our schedule, currently due to rapid development, we may bring new features or fix bugs everyday, resulting in some difficulty in version control.

For now, I recommend you trying these steps:
1. in your `tispark` directory, execute
```bash
./bin/build-client.sh
```
to build `tikv-client-0.1.0-SNAPSHOT.jar` and install to your local maven repository. This jar is needed for building `tispark`.
2. in your `tispark` directory, execute
```bash
mvn clean install
```
to build `tispark-0.1.0-SNAPSHOT.jar` and install to your local maven repository.
3. You should be able to resolve `tispark` dependency in other projects on your local machine.

Regards.

**Comment by seufagner** [comment]
@Novemser, if the motivations is development velocity and project growth, It's sounds good :)

Now I was able to generate jar file and works fine!

Thanks for your reply
