### ISSUE TITLE
通过tispark查询某张表的时候提示table not exist

### ISSUE THREAD

**Issue by powqabc** [pingcap/tispark#393]
通过mysql-client查询某张表的时候是正常的
![image](https://user-images.githubusercontent.com/10123620/42809322-f2316dc2-89e7-11e8-8656-ce0b346ff502.png)
通过tispark查询的时候提示Table not exist
![image](https://user-images.githubusercontent.com/10123620/42809348-0a16f0e2-89e8-11e8-8160-c1ff59058b3e.png)
tispark的版本如下
![image](https://user-images.githubusercontent.com/10123620/42809371-19fcaede-89e8-11e8-8348-068905e2a808.png)

**Comment by birdstorm** [comment]
目前我这边还无法重现，请问这些表是怎么建的呢？您可以尝试重新导入这张表看看。

**Comment by powqabc** [comment]
@birdstorm 去mysql那边查询建表语句，然后copy到mysql客户端在tidb下面创建表。
重建之后是正常的。

**Comment by birdstorm** [comment]
> 然后copy到mysql客户端在tidb下面创建表

@powqabc 您好，能更详细描述一下你的建表流程么? 另外，

> 重建之后是正常的。

是否意味现在问题已解决？

**Comment by powqabc** [comment]
@birdstorm 
1. mysql客户端连接tidb
2. 在tidb里create database tidb_mycat_creditcloud; use tidb_mycat_creditcloud;
3. 在mysql里查询show create table pre_loan_apply_info;
4. copy建表语句到tidb里执行
5. 通过jdbc方式写入数据

现在找不到出错的原因，那唯一的办法就只能重建表重新导数据了。但是怕以后再遇到同样的问题，会对数据分析人员使用tispark分析的时候造成困扰，而且当表的数据量大了之后，重建表重导数据是个麻烦事

**Comment by birdstorm** [comment]
@powqabc 这个问题可以稳定重现吗

**Comment by powqabc** [comment]
@birdstorm 这不是一张新表，里面已经有几千万条数据了

**Comment by melin** [comment]
确实比较难重现。有三四千张tidb表，三四张表有这个问题

**Comment by birdstorm** [comment]
Conclusion: 

Bug in ScanIterator caused seldom `table not exists`. 

When currentCache is null means no keys found, whereas currentCache is empty means no values found. The difference lies in whether to continue scanning, because chances are that the same key is split in another region because of pending entries, region split, e.t.c.

e.g., Assume we fetch table information in DB:123, ScanIterator sends a request containing an encoded key, say [1,2,3,0,0,0,1], and finds the first region that contains this key. If the region's range(e.g., [[1,2,3,0,0,0,0], [1,2,3,0,0,1,1])) was not enough to cover all keys [1,2,3,0,0,0,1], it is possible that it returns a partial result because some other table meta are contained in another region(e.g., [[1,2,3,0,0,1,1], [1,2,3,0,0,2])). 

Because ScanIterator was only used in fetching table meta info, tests not covering thousands of tables are unable to reveal this bug beforehand.
