### ISSUE TITLE
Add interface in TiContext to map all database in tidb?

### ISSUE THREAD

**Issue by shalcanleo** [pingcap/tispark#452]
MetaManager has method: def getDatabases: List[TiDBInfo].
Could you please add method in TiContext to map all db to sqlContext like tidbMapDatabase?

**Comment by birdstorm** [comment]
Hi, @shalcanleo 

Thanks for your feedback. As we are moving to support Spark 2.3+, you will be able to read all databases and tables in TiDB without calling `tidbMapDatabase` after PR #360 is merged. 

It is not a good idea for TiContext to map all databases as it was a naive approach for mapping all physic tables into TempViews. When duplicate table names encounters in different databases, you will have to use the `dbNameAsPrefix` option to distinguish those tables. (which was pretty nasty)

Since #360, you can use `use $databaseName` syntax to specify TiDB databases or `select a from dbName.tableName` syntax to specify respective TiDB tables. The changes will be merged in a day or two. Hope you will enjoy the new feature:)

**Comment by shalcanleo** [comment]
That's COOL! Thanks a lot. But when will the next version release to use this?

**Comment by birdstorm** [comment]
You will get them by release 2.0. :) We also welcome more issues and testing on the current master branch!
