### ISSUE TITLE
Calculation pushdown

### ISSUE THREAD

**Issue by billhcmus** [pingcap/tispark#934]
Hi all,

I new researcher with TiSpark and TiDB,
According to this docs: https://github.com/pingcap/tispark/blob/master/docs/userguide.md#overview
In TiSpark Architecture:

`It utilizes several strategies to push down the computing to reduce the size of dataset handling by Spark SQL, which accelerates the query execution. It also uses the TiDB built-in statistical information for the query plan optimization.`

I'm confused here, I have an example like below:

```sql
select sum(balance) from accounts
```
My question is: Is TiSpark push the `sum` calculation down to TiKV coprocessor?
And in the second phase: `It also uses the TiDB built-in statistical information for the query plan optimization.` what is this? what is information? In my understanding, TiSpark work with PD and TiKV, not TiDB.

**Comment by birdstorm** [comment]
@billhcmus Hi, nice questions. 

For your first question in short, yes, TiSpark pushes sum to TiKV and does a partial sum of the result. You may check the plan by explaining the sql for details.

Statistical information contains statistics of table and column/index information. It is used to sample the column data and make it better for optimizer to form a better physical plan. Since TiSpark has not yet support everything TiDB does -- TiSpark is distributed while TiDB is calculates in stand-alone mode, things like the statistical information and DDL depends on TiDB

**Comment by billhcmus** [comment]
Thank for your response, your answer clear my mind.
